name: ToolSwap
main: com.gmail.mmonkey.ToolSwap.ToolSwap
version: 1.4.1
commands:
   toolswap:
      description: Automatically switch tools, from your inventory, to your hand depending on what you are mining/fighting. If you have torches in your inventory, and a pickaxe or shovel in hand, right click to automatically switch to torches.
      usage: |
        /<command> [on] - Turn ToolSwap on.
        /<command> [off] - Turn ToolSwap off.
        /<command> [set] - Set a preferred tool. Turns on listening mode.
        /<command> [cancel] - Cancel listening mode.
        /<command> [list] - List of preferred tool preferences.
        /<command> [del] [number] - Delete tool preference with the given number.
        /<command> <player> [on] - Turn ToolSwap on for given player.
        /<command> <player> [off] - Turn TooolSwap off for given player.
permissions:
   toolswap.*:
      description: Gives access to all ToolSwap commands / functions
      children:
         toolswap.use: true
         toolswap.on: true
         toolswap.off: true
         toolswap.pref: true
         toolswap.player.on: true
         toolswap.player.off: true
      default: op
   toolswap.use:
      description: Allows player to use ToolSwap
      default: true
   toolswap.on:
      description: Allows player to turn ToolSwap on
      default: op
   toolswap.pref:
      description: Allows player to set ToolSwap to listening-mode
      default: op
   toolswap.off:
      description: Allows player to turn ToolSwap off
      default: op
   toolswap.player.on:
      description: Allows player to turn on ToolSwap for a specified player
      default: op
   toolswap.player.off:
      description: Allows player to turn off ToolSwap for a specified player
      default: op